export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  KANBAN: 'KANBAN',
  USERS: 'USERS',
  PLAY_BACKGROUND: 'PLAY_BACKGROUND',

  PRODUCT: 'PRODUCT',
  PRODUCT_ADD: 'PRODUCT_ADD',
  PRODUCT_LIST: 'PRODUCT_LIST',

  CATEGORY: 'CATEGORY',
  CATEGORY_ADD: 'CATEGORY_ADD',
  CATEGORY_LIST: 'CATEGORY_LIST',
};
