export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '/404',
  ERROR_403: '/403',
  DASHBOARD: '/dashboard',
  PLAY_BACKGROUND: '/playbackground',
  LOGIN: '/login',
  PRODUCT: '/product',
  PRODUCT_LIST: '/product/list',
  PRODUCT_ADD: '/product/add',
  CATEGORY: '/category',
  CATEGORY_LIST: '/category/list',
  CATEGORY_ADD: '/category/add',
  USERS: '/users',
  KANBAN: '/kanban',
  ORDER: '/order',
};
